imports:
  - { resource: ../common.yml }

services:
    product_comment_criterion_form_data_provider:
        class: 'Presta_Shop\Module\Product_Comment\Form\Product_Comment_Criterion_Form_Data_Provider'
        public: true
        arguments:
            - '@product_comment_criterion_repository'
            - '@prestashop.core.admin.lang.repository'
            
    product_comment_criterion_form_data_handler:
        class: 'Presta_Shop\Module\Product_Comment\Form\Product_Comment_Criterion_Form_Data_Handler'
        public: true
        arguments:
            - '@product_comment_criterion_repository'
            - '@prestashop.core.admin.lang.repository'
            - '@doctrine.orm.default_entity_manager'